### ISSUE TITLE
Documents directory is not created if it does not already exist

### ISSUE THREAD

**Issue by tttppp** [ningyuansg/GPX-Recorder#1]
Many thanks for the app! I tried it out on two Android devices, and it didn't work on either because DIRECTORY_DOCUMENTS did not exist.  I was getting:

```System.err: java.io.FileNotFoundException: /storage/emulated/0/Documents/20170718_211303.gpx: open failed: ENOENT (No such file or directory)```

After creating the directory (with my file browser) then the app started working fine.

**Comment by tttppp** [comment]
This might be related to different versions of Android? https://stackoverflow.com/q/28036876/171296

**Comment by ning-y** [comment]
@tttppp Agreed. The app was written with `minSdkVersion 16`, while `DIRECTORY_DOCUMENTS` was introduced only in API 19, according to your stackoverflow link.

As a fix, I could either:

1. Bump the `minimumSdkVersion` to 19, or
2. Check (and create if not existing) a `documents` folder in storage for the file

Either way, I probably won't be working on this project anytime soon. I'm starting my next year in university soon, and as a result find myself needing to prioritise my work. Are you in urgent need of a fix?

`minSdkVersion 16`: https://github.com/ningyuansg/GPX-Recorder/blob/5580eba24b10d01a82c67157747b76d5497b9b53/app/build.gradle#L8
`DIRECTORY_DOCUMENTS`: https://github.com/ningyuansg/GPX-Recorder/blob/5580eba24b10d01a82c67157747b76d5497b9b53/app/src/main/java/io/ningyuan/gpslogger/GpxFile.java#L22

**Comment by ning-y** [comment]
Nevermind, just saw your pull request. Will take a look and update when I can.

**Comment by tttppp** [comment]
Sorry - I should have made it clearer that I intended to try and fix this!  I think you've made a nice little app, and it was the only one I could find with no need for internet access.

I think the pull request fixes this problem, and also adds some feedback to show where the gpx files are stored.

Many thanks!

**Comment by ning-y** [comment]
@tttppp 

I was unable to find the .jks keyfile I used to sign this apk, and as such am unable to update the app on the app store. Additionally, I can't really justify the commitment to keep this app undated.

But please feel free to clone/fork otherwise take control of this source code (or easily write a better one). I will leave whatever I can leave of this project to the public domain.
